import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Qpaw</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/dog-paw.png" />
      </Head>
      <main className={`flex min-h-screen flex-col bg-blue-400`}>
       Home Page
      </main>
    </>
  );
}
